package com.wnp.lqmall.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.simplexx.wnp.repository.entity.NotifyHistory;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig notifyHistoryDaoConfig;

    private final NotifyHistoryDao notifyHistoryDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        notifyHistoryDaoConfig = daoConfigMap.get(NotifyHistoryDao.class).clone();
        notifyHistoryDaoConfig.initIdentityScope(type);

        notifyHistoryDao = new NotifyHistoryDao(notifyHistoryDaoConfig, this);

        registerDao(NotifyHistory.class, notifyHistoryDao);
    }
    
    public void clear() {
        notifyHistoryDaoConfig.clearIdentityScope();
    }

    public NotifyHistoryDao getNotifyHistoryDao() {
        return notifyHistoryDao;
    }

}
